[project]
name = "redis-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["redis>=5.2.1"]

[dependency-groups]
dev = ["ruff>=0.9.4"]
